-- 2013-07-15
CREATE TABLE icd_user (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL,
    `password` VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL
);

SELECT * FROM icd_user;